.PHONY: all

all: iaddr iaton intoa ntop_pton

iaddr:
	gcc -o inet_addr_example inet_addr_ex.c 

iaton:
	gcc -o inet_aton_example inet_aton_ex.c

intoa:
	gcc -o inet_ntoa_example inet_aton_ex.c

ntop_pton:
	gcc -o inet_ntop_pton_example inet_ntop_pton_ex.c

clean:
	rm inet_addr_example inet_aton_example inet_ntoa_example inet_ntop_pton_example